#!/bin/sh
. ~/.config/HyprV/hyprv.conf

#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "refresh style config"

#set the waybar theme
ln -sf ~/.config/HyprV/waybar/style/style.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/HyprV/wofi/style/style.css ~/.config/wofi/style.css

#set the mako theme
ln -sf ~/.config/HyprV/mako/conf/config ~/.config/mako/config

#set the measuring unit
ln -sf ~/.config/HyprV/waybar/conf/mesu-met.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc

#set the xfce and GTK theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"


#change the background image and be cool about it ;)
if [ -z $SET_BG ]; then
    swww img ~/.config/HyprV/backgrounds/background.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
else
    swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
fi

#update the sddm image
cp -f ~/.config/HyprV/backgrounds/background.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#reset mako
sleep 1
pkill mako
mako &

#restart the waybar
#killall -SIGUSR2 waybar <-- start causing web brwsers to close so switched to below...
pkill waybar
waybar &
