#!/bin/bash
. ~/.config/HyprV/hyprv.conf

restart_waybar() {
    #restart the waybar
    pkill waybar
    waybar & 
}

set_current_background() {
    if [[ ! -z "$SET_BG" ]]; then
        #set the current background
        swww img ~/.config/HyprV/backgrounds/background.jpg
    else
        swww img $SET_BG
    fi
}

switch_keyboard() {
    hyprctl switchxkblayout $SET_KB next
}

if [[ "$1" == "vswitch" ]]; then
    restart_waybar
elif [[ "$1" == "setbg" ]]; then
    set_current_background
    restart_waybar
elif [[ "$1" == "swkb" ]]; then
    switch_keyboard
    restart_waybar
fi

TOOLTIP='Default Keybinds\n'\
'SUPER + ENTER = Start Terminal\n'\
'SUPER + E = Toogle floating\n'\
'SUPER + D = App Launcher\n'\
'SUPER + F = Full Screen\n'\
'SUPER + G = File Manager\n'\
'SUPER + P = Screenshot\n'\
'SUPER + Q = Close Window\n'\
'SUPER + R = Rotate layout\n'\
'SUPER + S = Switch Keyboard Layout\n'\
'SUPER + SPACE = Invoke Notification Action\n'\
'SUPER + ESC = Dismiss Notification\n'\
'SUPER + SHIFT + SPACE = Restore Dismissed Notifications\n'\
'SUPER + SHIFG + X = Lock Screen\n'\
'SUPER + SHIFT + S = Logout menu\n'\
'SUPER + 0-9 = Change Workspace\n'\
'SUPER + H/J/K/L = Change Focused Window\n'\
'SUPER + SHIFT + Y/U/I/O = Resize Focused Window\n'\
'SUPER + SHIFT + V = Open clipboard manager'

echo '{"text": "keymap", "tooltip": "'$TOOLTIP'"}'